name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.2
      - name: Copy files via scp
        run: ls ${{ github.workspace }}